export default function Head() {
  return (
    <>
      <title>KiRA</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by KiRA" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
